apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-app
  labels:
    app: template-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-app
  template:
    metadata:
      labels:
        app: template-app
    spec:
      containers:
        - name: template-container
          image: bohuang910407/fastapi-template:latest # Use the local registry image
          ports:
            - containerPort: 8000 # Exposing port 8000 since FastAPI runs on this port
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: template-service
spec:
  type: LoadBalancer # Use LoadBalancer or NodePort based on your k3d setup
  ports:
    - port: 80 # External port to access the service
      targetPort: 8000 # The port where the FastAPI app is listening inside the container
  selector:
    app: template-app